### ISSUE TITLE
Report error, when no CouchDB binary found, instead of failing

### ISSUE THREAD

**Issue by janl** [hoodiehq/node-multicouch#27]
Via https://github.com/hoodiehq/hood.ie/issues/196 by @thomasvs.

The problem is in node-multitouch. I just explained the situation to @Charlotteis in Slack, but I thought it is worth capturing here:

The function `system_couch` (https://github.com/hoodiehq/node-multicouch/blob/master/lib/multicouch.js#L138) tries to find a CouchDB installation on your system, and then return the path to where that CouchDB installation lives, along with it’s associated `default.ini` path (see #170 where we return these two things)

There are various ways how people can install CouchDB, so we are trying them all

In #141 we check if someone provided us with the environment variable `COUCHDB_PATH` that points to what we need to return. #143 returns the final paths.

#149: if there is no environment variable, we use the unix `which` utility, which I believe works on both windows and unix (incl. linux & mac)

`which` gives us the path to a binary, you can run it in your Terminal, run `which node` and it will print the full path to the `node` binary, in my case:
> which node
> /usr/local/bin/node

ignore #158-161, that’s magic.

#163, should `which` not find what we need (it usually only looks inside the directories that are listed in the `$PATH` environment variable (to see its contents, run `echo $PATH`), we run a little utility script. That script is `bin/launch-couchdb-from.app.sh`

The `bin/launch-couchdb-from.app.sh` script only works on Mac OS X, it uses the system built-in `mdfind` utility on the command line.

So only if we don’t have an env var, and which fails, we drop to that Mac specific way of launching CouchDB. (btw, that’s the thing that just allows you to download the CouchDB app from couchdb.apache.org instead of doing a lengthy homebrew or so install)

Now, in @thomasvs’s case: no env var, `which` fails, because CouchDB isn’t installed, and the `bin/launch-couchdb-from.app.sh` fails, because it is run on not a Mac.

What we need now is 1. make sure we only ever run `bin/launch-couchdb-from.app.sh` when we are on a Mac, and 2. If all our methods of determining the two paths we are after fail, report an error.

**Comment by janl** [comment]
Final hint, to figure out if you run on a Mac, `console.log` (in Node) you the `process` global variable, and look for `darwin` or look though https://nodejs.org/api/process.html.

**Comment by freya-m** [comment]
Hi @janl,

Please forgive me if this post is in the wrong spot or doesn't apply to you or I am completely inept. I'm new to GitHub and to Open Source.

I'm not sure about the first part of this issue, because I don't know much about code (and even less about Node.js). My guess is that there's a library out there somewhere to detect OS name/version... This could be used to check which operating system the user has, and then run the script if it is a Mac.

I have taken a stab at writing an error message as well. " 'default.ini' could not be found. Please check that CouchDB is installed [where CouchDB installation files should live], and try again. "

Cheers!

**Comment by mccullagh** [comment]
The issue has been fixed in https://github.com/hoodiehq/node-multicouch/commit/3c0588db6bee25c94b34b82585aa896626698901
